# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import app_pb2 as app__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in app_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AppStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamEvents = channel.stream_stream(
                '/proto.App/StreamEvents',
                request_serializer=app__pb2.Event.SerializeToString,
                response_deserializer=app__pb2.Event.FromString,
                _registered_method=True)
        self.ValidateLogin = channel.unary_unary(
                '/proto.App/ValidateLogin',
                request_serializer=app__pb2.ValidateLoginRequest.SerializeToString,
                response_deserializer=app__pb2.ValidateLoginResponse.FromString,
                _registered_method=True)
        self.LoggedIn = channel.unary_unary(
                '/proto.App/LoggedIn',
                request_serializer=app__pb2.LoggedInRequest.SerializeToString,
                response_deserializer=app__pb2.LoggedInResponse.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/proto.App/GetSession',
                request_serializer=app__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=app__pb2.GetSessionResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/proto.App/Logout',
                request_serializer=app__pb2.LogoutRequest.SerializeToString,
                response_deserializer=app__pb2.LogoutResponse.FromString,
                _registered_method=True)
        self.ListSamples = channel.unary_unary(
                '/proto.App/ListSamples',
                request_serializer=app__pb2.ListSamplesRequest.SerializeToString,
                response_deserializer=app__pb2.ListSamplesResponse.FromString,
                _registered_method=True)
        self.SearchSamples = channel.unary_unary(
                '/proto.App/SearchSamples',
                request_serializer=app__pb2.SearchSampleRequest.SerializeToString,
                response_deserializer=app__pb2.SearchSampleResponse.FromString,
                _registered_method=True)
        self.SampleInfo = channel.unary_unary(
                '/proto.App/SampleInfo',
                request_serializer=app__pb2.SampleInfoRequest.SerializeToString,
                response_deserializer=app__pb2.SampleInfoResponse.FromString,
                _registered_method=True)
        self.ListSamplePacks = channel.unary_unary(
                '/proto.App/ListSamplePacks',
                request_serializer=app__pb2.ListSamplePacksRequest.SerializeToString,
                response_deserializer=app__pb2.ListSamplePacksResponse.FromString,
                _registered_method=True)
        self.DownloadSample = channel.unary_unary(
                '/proto.App/DownloadSample',
                request_serializer=app__pb2.DownloadSampleRequest.SerializeToString,
                response_deserializer=app__pb2.DownloadSampleResponse.FromString,
                _registered_method=True)
        self.SyncSounds = channel.unary_unary(
                '/proto.App/SyncSounds',
                request_serializer=app__pb2.SyncSoundsRequest.SerializeToString,
                response_deserializer=app__pb2.SyncSoundsResponse.FromString,
                _registered_method=True)
        self.CancelSampleDownload = channel.unary_unary(
                '/proto.App/CancelSampleDownload',
                request_serializer=app__pb2.CancelSampleDownloadRequest.SerializeToString,
                response_deserializer=app__pb2.CancelSampleDownloadResponse.FromString,
                _registered_method=True)
        self.InstallPlugin = channel.unary_unary(
                '/proto.App/InstallPlugin',
                request_serializer=app__pb2.InstallPluginRequest.SerializeToString,
                response_deserializer=app__pb2.InstallPluginResponse.FromString,
                _registered_method=True)
        self.UpdatePlugin = channel.unary_unary(
                '/proto.App/UpdatePlugin',
                request_serializer=app__pb2.UpdatePluginRequest.SerializeToString,
                response_deserializer=app__pb2.UpdatePluginResponse.FromString,
                _registered_method=True)
        self.CancelPluginDownload = channel.unary_unary(
                '/proto.App/CancelPluginDownload',
                request_serializer=app__pb2.CancelPluginDownloadRequest.SerializeToString,
                response_deserializer=app__pb2.CancelPluginDownloadResponse.FromString,
                _registered_method=True)
        self.UserPreferences = channel.unary_unary(
                '/proto.App/UserPreferences',
                request_serializer=app__pb2.UserPreferencesRequest.SerializeToString,
                response_deserializer=app__pb2.UserPreferencesResponse.FromString,
                _registered_method=True)
        self.UpdateUserPreferences = channel.unary_unary(
                '/proto.App/UpdateUserPreferences',
                request_serializer=app__pb2.UpdateUserPreferencesRequest.SerializeToString,
                response_deserializer=app__pb2.UpdateUserPreferencesResponse.FromString,
                _registered_method=True)
        self.DownloadLogs = channel.unary_unary(
                '/proto.App/DownloadLogs',
                request_serializer=app__pb2.DownloadLogsRequest.SerializeToString,
                response_deserializer=app__pb2.DownloadLogsResponse.FromString,
                _registered_method=True)
        self.CopyFileToClipboard = channel.unary_unary(
                '/proto.App/CopyFileToClipboard',
                request_serializer=app__pb2.CopyFileToClipboardRequest.SerializeToString,
                response_deserializer=app__pb2.CopyFileToClipboardResponse.FromString,
                _registered_method=True)
        self.ConvertToWav = channel.unary_unary(
                '/proto.App/ConvertToWav',
                request_serializer=app__pb2.ConvertToWavRequest.SerializeToString,
                response_deserializer=app__pb2.ConvertToWavResponse.FromString,
                _registered_method=True)
        self.ProjectDiskScan = channel.unary_unary(
                '/proto.App/ProjectDiskScan',
                request_serializer=app__pb2.ProjectDiskScanRequest.SerializeToString,
                response_deserializer=app__pb2.ProjectDiskScanResponse.FromString,
                _registered_method=True)
        self.CancelProjectDiskScan = channel.unary_unary(
                '/proto.App/CancelProjectDiskScan',
                request_serializer=app__pb2.CancelProjectDiskScanRequest.SerializeToString,
                response_deserializer=app__pb2.CancelProjectDiskScanResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/proto.App/Shutdown',
                request_serializer=app__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=app__pb2.ShutdownResponse.FromString,
                _registered_method=True)
        self.ConvertSoundsTrial = channel.unary_unary(
                '/proto.App/ConvertSoundsTrial',
                request_serializer=app__pb2.ConvertSoundsTrialRequest.SerializeToString,
                response_deserializer=app__pb2.ConvertSoundsTrialResponse.FromString,
                _registered_method=True)
        self.SendFeedback = channel.unary_unary(
                '/proto.App/SendFeedback',
                request_serializer=app__pb2.SendFeedbackRequest.SerializeToString,
                response_deserializer=app__pb2.SendFeedbackResponse.FromString,
                _registered_method=True)
        self.InstallAppFromChannel = channel.unary_unary(
                '/proto.App/InstallAppFromChannel',
                request_serializer=app__pb2.InstallAppFromChannelRequest.SerializeToString,
                response_deserializer=app__pb2.InstallAppFromChannelResponse.FromString,
                _registered_method=True)
        self.CollectionAdd = channel.unary_unary(
                '/proto.App/CollectionAdd',
                request_serializer=app__pb2.CollectionAddRequest.SerializeToString,
                response_deserializer=app__pb2.CollectionAddResponse.FromString,
                _registered_method=True)
        self.CollectionAddItems = channel.unary_unary(
                '/proto.App/CollectionAddItems',
                request_serializer=app__pb2.CollectionAddItemsRequest.SerializeToString,
                response_deserializer=app__pb2.CollectionAddItemsResponse.FromString,
                _registered_method=True)
        self.CollectionsList = channel.unary_unary(
                '/proto.App/CollectionsList',
                request_serializer=app__pb2.CollectionsListRequest.SerializeToString,
                response_deserializer=app__pb2.CollectionsListResponse.FromString,
                _registered_method=True)
        self.CollectionUpdate = channel.unary_unary(
                '/proto.App/CollectionUpdate',
                request_serializer=app__pb2.CollectionUpdateRequest.SerializeToString,
                response_deserializer=app__pb2.CollectionUpdateResponse.FromString,
                _registered_method=True)
        self.CollectionDelete = channel.unary_unary(
                '/proto.App/CollectionDelete',
                request_serializer=app__pb2.CollectionDeleteRequest.SerializeToString,
                response_deserializer=app__pb2.CollectionDeleteResponse.FromString,
                _registered_method=True)
        self.CollectionDeleteItems = channel.unary_unary(
                '/proto.App/CollectionDeleteItems',
                request_serializer=app__pb2.CollectionDeleteItemsRequest.SerializeToString,
                response_deserializer=app__pb2.CollectionDeleteItemsResponse.FromString,
                _registered_method=True)
        self.CollectionListSamples = channel.unary_unary(
                '/proto.App/CollectionListSamples',
                request_serializer=app__pb2.CollectionListSamplesRequest.SerializeToString,
                response_deserializer=app__pb2.CollectionListSamplesResponse.FromString,
                _registered_method=True)
        self.PresetsListPurchased = channel.unary_unary(
                '/proto.App/PresetsListPurchased',
                request_serializer=app__pb2.PresetsListPurchasedRequest.SerializeToString,
                response_deserializer=app__pb2.PresetsListPurchasedResponse.FromString,
                _registered_method=True)
        self.PresetDownload = channel.unary_unary(
                '/proto.App/PresetDownload',
                request_serializer=app__pb2.PresetDownloadRequest.SerializeToString,
                response_deserializer=app__pb2.PresetDownloadResponse.FromString,
                _registered_method=True)
        self.UnlicensedPresetDownload = channel.unary_unary(
                '/proto.App/UnlicensedPresetDownload',
                request_serializer=app__pb2.UnlicensedPresetDownloadRequest.SerializeToString,
                response_deserializer=app__pb2.UnlicensedPresetDownloadResponse.FromString,
                _registered_method=True)
        self.PresetsDownloadCancel = channel.unary_unary(
                '/proto.App/PresetsDownloadCancel',
                request_serializer=app__pb2.PresetsDownloadCancelRequest.SerializeToString,
                response_deserializer=app__pb2.PresetsDownloadCancelResponse.FromString,
                _registered_method=True)
        self.PresetPurchase = channel.unary_unary(
                '/proto.App/PresetPurchase',
                request_serializer=app__pb2.PresetPurchaseRequest.SerializeToString,
                response_deserializer=app__pb2.PresetPurchaseResponse.FromString,
                _registered_method=True)
        self.PresetInfo = channel.unary_unary(
                '/proto.App/PresetInfo',
                request_serializer=app__pb2.PresetInfoRequest.SerializeToString,
                response_deserializer=app__pb2.PresetInfoResponse.FromString,
                _registered_method=True)
        self.UpdatedSession = channel.unary_unary(
                '/proto.App/UpdatedSession',
                request_serializer=app__pb2.UpdatedSessionRequest.SerializeToString,
                response_deserializer=app__pb2.UpdatedSessionResponse.FromString,
                _registered_method=True)
        self.UpdatedFlags = channel.unary_unary(
                '/proto.App/UpdatedFlags',
                request_serializer=app__pb2.UpdatedFlagsRequest.SerializeToString,
                response_deserializer=app__pb2.UpdatedFlagsResponse.FromString,
                _registered_method=True)
        self.CountPresetsToClean = channel.unary_unary(
                '/proto.App/CountPresetsToClean',
                request_serializer=app__pb2.CountPresetsToCleanRequest.SerializeToString,
                response_deserializer=app__pb2.CountPresetsToCleanResponse.FromString,
                _registered_method=True)
        self.CleanPresets = channel.unary_unary(
                '/proto.App/CleanPresets',
                request_serializer=app__pb2.CleanPresetsRequest.SerializeToString,
                response_deserializer=app__pb2.CleanPresetsResponse.FromString,
                _registered_method=True)
        self.SyncPresets = channel.unary_unary(
                '/proto.App/SyncPresets',
                request_serializer=app__pb2.SyncPresetsRequest.SerializeToString,
                response_deserializer=app__pb2.SyncPresetsResponse.FromString,
                _registered_method=True)


class AppServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamEvents(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateLogin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoggedIn(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSamples(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchSamples(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SampleInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSamplePacks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadSample(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncSounds(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelSampleDownload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InstallPlugin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePlugin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelPluginDownload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UserPreferences(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserPreferences(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DownloadLogs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CopyFileToClipboard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConvertToWav(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProjectDiskScan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelProjectDiskScan(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConvertSoundsTrial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InstallAppFromChannel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectionAdd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectionAddItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectionsList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectionUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectionDelete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectionDeleteItems(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CollectionListSamples(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PresetsListPurchased(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PresetDownload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnlicensedPresetDownload(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PresetsDownloadCancel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PresetPurchase(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PresetInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatedSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatedFlags(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CountPresetsToClean(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CleanPresets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncPresets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AppServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamEvents': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=app__pb2.Event.FromString,
                    response_serializer=app__pb2.Event.SerializeToString,
            ),
            'ValidateLogin': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateLogin,
                    request_deserializer=app__pb2.ValidateLoginRequest.FromString,
                    response_serializer=app__pb2.ValidateLoginResponse.SerializeToString,
            ),
            'LoggedIn': grpc.unary_unary_rpc_method_handler(
                    servicer.LoggedIn,
                    request_deserializer=app__pb2.LoggedInRequest.FromString,
                    response_serializer=app__pb2.LoggedInResponse.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=app__pb2.GetSessionRequest.FromString,
                    response_serializer=app__pb2.GetSessionResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=app__pb2.LogoutRequest.FromString,
                    response_serializer=app__pb2.LogoutResponse.SerializeToString,
            ),
            'ListSamples': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSamples,
                    request_deserializer=app__pb2.ListSamplesRequest.FromString,
                    response_serializer=app__pb2.ListSamplesResponse.SerializeToString,
            ),
            'SearchSamples': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchSamples,
                    request_deserializer=app__pb2.SearchSampleRequest.FromString,
                    response_serializer=app__pb2.SearchSampleResponse.SerializeToString,
            ),
            'SampleInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.SampleInfo,
                    request_deserializer=app__pb2.SampleInfoRequest.FromString,
                    response_serializer=app__pb2.SampleInfoResponse.SerializeToString,
            ),
            'ListSamplePacks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSamplePacks,
                    request_deserializer=app__pb2.ListSamplePacksRequest.FromString,
                    response_serializer=app__pb2.ListSamplePacksResponse.SerializeToString,
            ),
            'DownloadSample': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadSample,
                    request_deserializer=app__pb2.DownloadSampleRequest.FromString,
                    response_serializer=app__pb2.DownloadSampleResponse.SerializeToString,
            ),
            'SyncSounds': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncSounds,
                    request_deserializer=app__pb2.SyncSoundsRequest.FromString,
                    response_serializer=app__pb2.SyncSoundsResponse.SerializeToString,
            ),
            'CancelSampleDownload': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelSampleDownload,
                    request_deserializer=app__pb2.CancelSampleDownloadRequest.FromString,
                    response_serializer=app__pb2.CancelSampleDownloadResponse.SerializeToString,
            ),
            'InstallPlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.InstallPlugin,
                    request_deserializer=app__pb2.InstallPluginRequest.FromString,
                    response_serializer=app__pb2.InstallPluginResponse.SerializeToString,
            ),
            'UpdatePlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePlugin,
                    request_deserializer=app__pb2.UpdatePluginRequest.FromString,
                    response_serializer=app__pb2.UpdatePluginResponse.SerializeToString,
            ),
            'CancelPluginDownload': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelPluginDownload,
                    request_deserializer=app__pb2.CancelPluginDownloadRequest.FromString,
                    response_serializer=app__pb2.CancelPluginDownloadResponse.SerializeToString,
            ),
            'UserPreferences': grpc.unary_unary_rpc_method_handler(
                    servicer.UserPreferences,
                    request_deserializer=app__pb2.UserPreferencesRequest.FromString,
                    response_serializer=app__pb2.UserPreferencesResponse.SerializeToString,
            ),
            'UpdateUserPreferences': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserPreferences,
                    request_deserializer=app__pb2.UpdateUserPreferencesRequest.FromString,
                    response_serializer=app__pb2.UpdateUserPreferencesResponse.SerializeToString,
            ),
            'DownloadLogs': grpc.unary_unary_rpc_method_handler(
                    servicer.DownloadLogs,
                    request_deserializer=app__pb2.DownloadLogsRequest.FromString,
                    response_serializer=app__pb2.DownloadLogsResponse.SerializeToString,
            ),
            'CopyFileToClipboard': grpc.unary_unary_rpc_method_handler(
                    servicer.CopyFileToClipboard,
                    request_deserializer=app__pb2.CopyFileToClipboardRequest.FromString,
                    response_serializer=app__pb2.CopyFileToClipboardResponse.SerializeToString,
            ),
            'ConvertToWav': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertToWav,
                    request_deserializer=app__pb2.ConvertToWavRequest.FromString,
                    response_serializer=app__pb2.ConvertToWavResponse.SerializeToString,
            ),
            'ProjectDiskScan': grpc.unary_unary_rpc_method_handler(
                    servicer.ProjectDiskScan,
                    request_deserializer=app__pb2.ProjectDiskScanRequest.FromString,
                    response_serializer=app__pb2.ProjectDiskScanResponse.SerializeToString,
            ),
            'CancelProjectDiskScan': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelProjectDiskScan,
                    request_deserializer=app__pb2.CancelProjectDiskScanRequest.FromString,
                    response_serializer=app__pb2.CancelProjectDiskScanResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=app__pb2.ShutdownRequest.FromString,
                    response_serializer=app__pb2.ShutdownResponse.SerializeToString,
            ),
            'ConvertSoundsTrial': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertSoundsTrial,
                    request_deserializer=app__pb2.ConvertSoundsTrialRequest.FromString,
                    response_serializer=app__pb2.ConvertSoundsTrialResponse.SerializeToString,
            ),
            'SendFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.SendFeedback,
                    request_deserializer=app__pb2.SendFeedbackRequest.FromString,
                    response_serializer=app__pb2.SendFeedbackResponse.SerializeToString,
            ),
            'InstallAppFromChannel': grpc.unary_unary_rpc_method_handler(
                    servicer.InstallAppFromChannel,
                    request_deserializer=app__pb2.InstallAppFromChannelRequest.FromString,
                    response_serializer=app__pb2.InstallAppFromChannelResponse.SerializeToString,
            ),
            'CollectionAdd': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectionAdd,
                    request_deserializer=app__pb2.CollectionAddRequest.FromString,
                    response_serializer=app__pb2.CollectionAddResponse.SerializeToString,
            ),
            'CollectionAddItems': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectionAddItems,
                    request_deserializer=app__pb2.CollectionAddItemsRequest.FromString,
                    response_serializer=app__pb2.CollectionAddItemsResponse.SerializeToString,
            ),
            'CollectionsList': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectionsList,
                    request_deserializer=app__pb2.CollectionsListRequest.FromString,
                    response_serializer=app__pb2.CollectionsListResponse.SerializeToString,
            ),
            'CollectionUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectionUpdate,
                    request_deserializer=app__pb2.CollectionUpdateRequest.FromString,
                    response_serializer=app__pb2.CollectionUpdateResponse.SerializeToString,
            ),
            'CollectionDelete': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectionDelete,
                    request_deserializer=app__pb2.CollectionDeleteRequest.FromString,
                    response_serializer=app__pb2.CollectionDeleteResponse.SerializeToString,
            ),
            'CollectionDeleteItems': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectionDeleteItems,
                    request_deserializer=app__pb2.CollectionDeleteItemsRequest.FromString,
                    response_serializer=app__pb2.CollectionDeleteItemsResponse.SerializeToString,
            ),
            'CollectionListSamples': grpc.unary_unary_rpc_method_handler(
                    servicer.CollectionListSamples,
                    request_deserializer=app__pb2.CollectionListSamplesRequest.FromString,
                    response_serializer=app__pb2.CollectionListSamplesResponse.SerializeToString,
            ),
            'PresetsListPurchased': grpc.unary_unary_rpc_method_handler(
                    servicer.PresetsListPurchased,
                    request_deserializer=app__pb2.PresetsListPurchasedRequest.FromString,
                    response_serializer=app__pb2.PresetsListPurchasedResponse.SerializeToString,
            ),
            'PresetDownload': grpc.unary_unary_rpc_method_handler(
                    servicer.PresetDownload,
                    request_deserializer=app__pb2.PresetDownloadRequest.FromString,
                    response_serializer=app__pb2.PresetDownloadResponse.SerializeToString,
            ),
            'UnlicensedPresetDownload': grpc.unary_unary_rpc_method_handler(
                    servicer.UnlicensedPresetDownload,
                    request_deserializer=app__pb2.UnlicensedPresetDownloadRequest.FromString,
                    response_serializer=app__pb2.UnlicensedPresetDownloadResponse.SerializeToString,
            ),
            'PresetsDownloadCancel': grpc.unary_unary_rpc_method_handler(
                    servicer.PresetsDownloadCancel,
                    request_deserializer=app__pb2.PresetsDownloadCancelRequest.FromString,
                    response_serializer=app__pb2.PresetsDownloadCancelResponse.SerializeToString,
            ),
            'PresetPurchase': grpc.unary_unary_rpc_method_handler(
                    servicer.PresetPurchase,
                    request_deserializer=app__pb2.PresetPurchaseRequest.FromString,
                    response_serializer=app__pb2.PresetPurchaseResponse.SerializeToString,
            ),
            'PresetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.PresetInfo,
                    request_deserializer=app__pb2.PresetInfoRequest.FromString,
                    response_serializer=app__pb2.PresetInfoResponse.SerializeToString,
            ),
            'UpdatedSession': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatedSession,
                    request_deserializer=app__pb2.UpdatedSessionRequest.FromString,
                    response_serializer=app__pb2.UpdatedSessionResponse.SerializeToString,
            ),
            'UpdatedFlags': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatedFlags,
                    request_deserializer=app__pb2.UpdatedFlagsRequest.FromString,
                    response_serializer=app__pb2.UpdatedFlagsResponse.SerializeToString,
            ),
            'CountPresetsToClean': grpc.unary_unary_rpc_method_handler(
                    servicer.CountPresetsToClean,
                    request_deserializer=app__pb2.CountPresetsToCleanRequest.FromString,
                    response_serializer=app__pb2.CountPresetsToCleanResponse.SerializeToString,
            ),
            'CleanPresets': grpc.unary_unary_rpc_method_handler(
                    servicer.CleanPresets,
                    request_deserializer=app__pb2.CleanPresetsRequest.FromString,
                    response_serializer=app__pb2.CleanPresetsResponse.SerializeToString,
            ),
            'SyncPresets': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncPresets,
                    request_deserializer=app__pb2.SyncPresetsRequest.FromString,
                    response_serializer=app__pb2.SyncPresetsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'proto.App', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('proto.App', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class App(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamEvents(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/proto.App/StreamEvents',
            app__pb2.Event.SerializeToString,
            app__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateLogin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/ValidateLogin',
            app__pb2.ValidateLoginRequest.SerializeToString,
            app__pb2.ValidateLoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoggedIn(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/LoggedIn',
            app__pb2.LoggedInRequest.SerializeToString,
            app__pb2.LoggedInResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/GetSession',
            app__pb2.GetSessionRequest.SerializeToString,
            app__pb2.GetSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/Logout',
            app__pb2.LogoutRequest.SerializeToString,
            app__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSamples(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/ListSamples',
            app__pb2.ListSamplesRequest.SerializeToString,
            app__pb2.ListSamplesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchSamples(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/SearchSamples',
            app__pb2.SearchSampleRequest.SerializeToString,
            app__pb2.SearchSampleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SampleInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/SampleInfo',
            app__pb2.SampleInfoRequest.SerializeToString,
            app__pb2.SampleInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSamplePacks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/ListSamplePacks',
            app__pb2.ListSamplePacksRequest.SerializeToString,
            app__pb2.ListSamplePacksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadSample(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/DownloadSample',
            app__pb2.DownloadSampleRequest.SerializeToString,
            app__pb2.DownloadSampleResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncSounds(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/SyncSounds',
            app__pb2.SyncSoundsRequest.SerializeToString,
            app__pb2.SyncSoundsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelSampleDownload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/CancelSampleDownload',
            app__pb2.CancelSampleDownloadRequest.SerializeToString,
            app__pb2.CancelSampleDownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InstallPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/InstallPlugin',
            app__pb2.InstallPluginRequest.SerializeToString,
            app__pb2.InstallPluginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/UpdatePlugin',
            app__pb2.UpdatePluginRequest.SerializeToString,
            app__pb2.UpdatePluginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelPluginDownload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/CancelPluginDownload',
            app__pb2.CancelPluginDownloadRequest.SerializeToString,
            app__pb2.CancelPluginDownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UserPreferences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/UserPreferences',
            app__pb2.UserPreferencesRequest.SerializeToString,
            app__pb2.UserPreferencesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserPreferences(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/UpdateUserPreferences',
            app__pb2.UpdateUserPreferencesRequest.SerializeToString,
            app__pb2.UpdateUserPreferencesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DownloadLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/DownloadLogs',
            app__pb2.DownloadLogsRequest.SerializeToString,
            app__pb2.DownloadLogsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CopyFileToClipboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/CopyFileToClipboard',
            app__pb2.CopyFileToClipboardRequest.SerializeToString,
            app__pb2.CopyFileToClipboardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConvertToWav(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/ConvertToWav',
            app__pb2.ConvertToWavRequest.SerializeToString,
            app__pb2.ConvertToWavResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProjectDiskScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/ProjectDiskScan',
            app__pb2.ProjectDiskScanRequest.SerializeToString,
            app__pb2.ProjectDiskScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelProjectDiskScan(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/CancelProjectDiskScan',
            app__pb2.CancelProjectDiskScanRequest.SerializeToString,
            app__pb2.CancelProjectDiskScanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/Shutdown',
            app__pb2.ShutdownRequest.SerializeToString,
            app__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConvertSoundsTrial(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/ConvertSoundsTrial',
            app__pb2.ConvertSoundsTrialRequest.SerializeToString,
            app__pb2.ConvertSoundsTrialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/SendFeedback',
            app__pb2.SendFeedbackRequest.SerializeToString,
            app__pb2.SendFeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InstallAppFromChannel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/InstallAppFromChannel',
            app__pb2.InstallAppFromChannelRequest.SerializeToString,
            app__pb2.InstallAppFromChannelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectionAdd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/CollectionAdd',
            app__pb2.CollectionAddRequest.SerializeToString,
            app__pb2.CollectionAddResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectionAddItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/CollectionAddItems',
            app__pb2.CollectionAddItemsRequest.SerializeToString,
            app__pb2.CollectionAddItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectionsList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/CollectionsList',
            app__pb2.CollectionsListRequest.SerializeToString,
            app__pb2.CollectionsListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectionUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/CollectionUpdate',
            app__pb2.CollectionUpdateRequest.SerializeToString,
            app__pb2.CollectionUpdateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectionDelete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/CollectionDelete',
            app__pb2.CollectionDeleteRequest.SerializeToString,
            app__pb2.CollectionDeleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectionDeleteItems(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/CollectionDeleteItems',
            app__pb2.CollectionDeleteItemsRequest.SerializeToString,
            app__pb2.CollectionDeleteItemsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CollectionListSamples(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/CollectionListSamples',
            app__pb2.CollectionListSamplesRequest.SerializeToString,
            app__pb2.CollectionListSamplesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PresetsListPurchased(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/PresetsListPurchased',
            app__pb2.PresetsListPurchasedRequest.SerializeToString,
            app__pb2.PresetsListPurchasedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PresetDownload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/PresetDownload',
            app__pb2.PresetDownloadRequest.SerializeToString,
            app__pb2.PresetDownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnlicensedPresetDownload(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/UnlicensedPresetDownload',
            app__pb2.UnlicensedPresetDownloadRequest.SerializeToString,
            app__pb2.UnlicensedPresetDownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PresetsDownloadCancel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/PresetsDownloadCancel',
            app__pb2.PresetsDownloadCancelRequest.SerializeToString,
            app__pb2.PresetsDownloadCancelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PresetPurchase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/PresetPurchase',
            app__pb2.PresetPurchaseRequest.SerializeToString,
            app__pb2.PresetPurchaseResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PresetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/PresetInfo',
            app__pb2.PresetInfoRequest.SerializeToString,
            app__pb2.PresetInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatedSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/UpdatedSession',
            app__pb2.UpdatedSessionRequest.SerializeToString,
            app__pb2.UpdatedSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatedFlags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/UpdatedFlags',
            app__pb2.UpdatedFlagsRequest.SerializeToString,
            app__pb2.UpdatedFlagsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CountPresetsToClean(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/CountPresetsToClean',
            app__pb2.CountPresetsToCleanRequest.SerializeToString,
            app__pb2.CountPresetsToCleanResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CleanPresets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/CleanPresets',
            app__pb2.CleanPresetsRequest.SerializeToString,
            app__pb2.CleanPresetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SyncPresets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/proto.App/SyncPresets',
            app__pb2.SyncPresetsRequest.SerializeToString,
            app__pb2.SyncPresetsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
